name: Deno
on: [push]

jobs:
  fmtlint:
    name: Lint / fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      
      - name: Lint / fmt
        run: |
          deno fmt
          deno lint
      - uses: chainguard-dev/actions/nodiff@main
        with:
          fixup-command: "deno fmt && deno lint"
  deploy:
    needs:
      - fmtlint
    strategy:
      matrix:
        include:
          - name: "httpdump"
            entrypoint: "./httpdump/httpdump.ts"
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - uses: actions/checkout@v2

      - uses: denoland/deployctl@v1
        with:
          # TODO(wilsonehusin): https://github.com/denoland/deploy_feedback/issues/17#issuecomment-1076532539
          import-map: "./import_map.json"
          project: ${{ matrix.name }}
          entrypoint: ${{ matrix.entrypoint }}