name: Deno
on: [push]

jobs:
  deploy:
    strategy:
      matrix:
        include:
          - name: "httpdump"
            entrypoint: "./httpdump/httpdump.ts"
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          # TODO(wilsonehusin): https://github.com/denoland/deploy_feedback/issues/17#issuecomment-1076532539
          import-map: "./import_map.json"
          project: ${{ matrix.name }}
          entrypoint: ${{ matrix.entrypoint }}